### ISSUE TITLE
AE2 Performance Issues Tracker

### ISSUE THREAD

**Issue by firenoo** [GTNewHorizons/Applied-Energistics-2-Unofficial#381]
Some performance issues to track/fix.
- [x] Interface terminal causes huge TPS drop (Server) https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/394
- [ ] On opening terminal, network usage spikes as AE2/addons send all items to the client (Both)
- [ ] While the terminal is open, there's a visible server TPS and client FPS drop (Both)
- [ ] Molecular assemblers are slow as they try to push every tick if there's no place for items to go (Server)
- [ ] Networks powered by quartz cable is slow (Server)
- [ ] Crafting calculations are slow, during simulation and runtime (Server)
- [ ] Crafting cards are bad for performance, likely deserves a redesign (Server)

**Comment by miaowwwwww** [comment]
is it possible to let networks with a neutron energy cell don't calculate energy usage at all? I do not know how much it could impact.

**Comment by Glease** [comment]
iirc the impact is insiginificant, or perhaps my implementation was flawed: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/371
